### ISSUE TITLE
compatibility with poppler

### ISSUE THREAD

**Issue by fossili** [Boomaga/boomaga#52] opened 2017-07-09 03:26 UTC
yesterday received poppler 0.41.0-0ubuntu**1.2** . Printing to boomaga results in no graphical display of printed document and empty page when printed on printer. Boomaga used was 0.91. Operating system Mint 18.1 and Mint 18.2 cinnamon. Version 0.41.0-0ubuntu**1.1** works. Backup was a good idea after all :) However it cannot stay like this. The new version of poppler seems to be offered for update very strongly...

**Comment by stormy-gh** [comment] 2017-07-10 14:28
Boomaga 0.9.1-1trusty has the same issue on Ubuntu 14.04.
I found that this change causes problem:
QDir().mkpath(outFileName + "/.."); ====> QFileInfo(outFileName).dir().mkpath(".");
The result is:
/usr/lib/x86_64-linux-gnu/boomaga/boomagamerger: symbol lookup error: /usr/lib/x86_64-linux-gnu/boomaga/boomagamerger: undefined symbol: _ZN6PDFDoc15markPageObjectsEP4DictP4XRefS3_j

To confirm this, I have changed this line back in source code and make deb. Boomaga start working again. So problem is caused by commit 61de231f90be73411ca1727a3aff5b4fa19f0d22 "Fixed Issue #50 Can't open file from .cache folder".

**Comment by SokoloffA** [comment] 2017-07-14 22:43
This is a duplicate of Issue https://github.com/Boomaga/boomaga/issues/53

**Comment by SokoloffA** [comment] 2017-07-20 19:46
**For Ubuntu guys**

Hi guys, I made the packages for different versions of Ubuntu and published they on [ppa](https://launchpad.net/~boomaga/+archive/ubuntu/ppa/+packages). I forced versions of libpoppler-dev. I hope this will solve our problems. Please leave feedback - is in your distributions the program works or not.

---

**For Mint guys**

Kick your maintainers, about to upgrade the package and specify depends like:
```
libpoppler-dev (>= 0.44.0-3ubuntu2.1)
```
Versions for different libpopplerXX can be found in .dsc files on my [ppa]( https://launchpad.net/~boomaga/+archive/ubuntu/ppa/+packages)

**Comment by budinero** [comment] 2017-10-11 20:08
Hi, I'm using boomaga in Arch. Since some days I get white pages documents when printing to boomaga. It's related to the poppler problem? Arch has 0.60.1 poppler version now. I tried to rebuid but with same results...

**Comment by SokoloffA** [comment] 2017-10-11 21:02
@budinero 
Yes this is problem with poppler on Arch https://github.com/Boomaga/boomaga/issues/56#issuecomment-333200746

Now I'm writing PDF parser from scrach.  So I hope the problems with the poppler will soon be gone.

**Comment by SokoloffA** [comment] 2017-11-05 19:59
I wrote my own PDF parser instead of poppler-private. Please test the [drop_poppler branch](https://github.com/Boomaga/boomaga/tree/drop_poppler).

**Comment by SokoloffA** [comment] 2018-03-22 17:32
Since the release of 1.0, the program does not use private poppler library to parse PDF files. So I'm closing the issue.

**Closed by SokoloffA** 2018-03-22 17:32 UTC
